import './globals.css'
import { Inter } from 'next/font/google'
import { redirect, usePathname } from 'next/navigation'
import Sidebar from './ui/Sidebar'
import Provider from './utility/Provider'
import useMediaQuery from '@/hooks/useMediaQuery'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'assignment project',
  description: 'Generated by Manthan kumar',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className='h-screen overflow-hidden  font-montserrat'>
        <Provider>{children}</Provider>
      </body>
    </html>
  )
}
